version: '3'
services:
  db:
    build: ./backend/database
    image: smwa-database:prod
    container_name: database
    volumes:
      - ./backend/database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi
      TZ: Asia/Tokyo
  
  server:
    build:
      context: ./backend/server
      dockerfile: Dockerfile.prod
    image: smwa-server:prod
    container_name: server
    command: bash -c "sleep 10 && echo starting server && uvicorn app.main:app --host 0.0.0.0 --port 8080"
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi
      POSTGRES_PORT: 5432
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: smwa-frontend:prod
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - server