version: '3'
services:
  db:
    build: ./database
    image: smwa-database:dev
    container_name: database-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi
      TZ: Asia/Tokyo
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: smwa-server:dev
    container_name: server-dev
    command: bash -c "sleep 10 && echo starting server && uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    volumes:
      - ./server/app:/app
    ports:
      - 8080:80
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi
      POSTGRES_PORT: 5432
    depends_on:
      - db